name: Update Task Definition
run-name: update_crd
on:
  push:
    branches:
      - main
jobs:
  update:
    uses: Aridhia-Open-Source/pipelines/.github/workflows/trigger-task.yml@main
    with:
      DEST_BRANCH: monitor
      TEMPLATE_PATH: crd/task-test-task-1.yaml
    secrets:
      SA_TOKEN: ${{ secrets.SA_TOKEN }}
