name: Update Task Definition
run-name: update_task
on:
  push:
    branches:
      - main
    paths:
      - argo/*.json

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    uses: Aridhia-Open-Source/pipelines/.github/workflows/trigger-task.yml@main
    with:
      # To change to the actual name
      DEST_BRANCH: argocd
      TEMPLATE_PATH: argo/task.json
    secrets:
      SA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
